### ISSUE TITLE
Workflow with highway_merge

### ISSUE THREAD

**Issue by matthiasfeist** [NKAmapper/highway_merge#1]
Hi.

Do you have an outline somewhere how a workflow would look like when using highway_merge with the Swedish NVDB OSM files?
I got your script to generate an OSM file (with -new or -replace) but from there I'm unsure of how to best get this imported into OSM.

**Comment by NKAmapper** [comment]
Done, please see README.
By the way, there are many municipalities/NVDB files missing for Sweden (no entry or error log), for example Jokkmokk and Arjeplog.
