### ISSUE TITLE
Problem with -swe

### ISSUE THREAD

**Issue by marsip** [NKAmapper/highway_merge#2]
I tried following:
python.exe .\highway_merge\highway_merge.py -replace Nora -swe

Got:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

Which certificate? How do I update?

**Comment by NKAmapper** [comment]
I am unable to reproduce this error. Google searching the error message indicates that there might be a problem with your Python install (certificates). Perhaps some of those suggestions might be of help.

**Comment by NKAmapper** [comment]
No bug in script.
